import { hero, kamar, dummyFoto  } from "../assets";

export const navLinks = [
  {
    id: "1",
    title: "Data Kamar",
    to: "/dataKamar",
  },
  {
    id: "2",
    title: "Data Tipe Kamar",
    to: "/dataTipeKamar",
  },
  {
    id: "3",
    title: "Data User",
    to: "/dataUser",
  },
];

export const DummyRoom = [
  {
    id: "1",
    Image: kamar,
    title: "Kamar Lavender Orichio",
    price: "Rp1.000.000 per malam",
    capacity: "2 Orang",
    type: "King Size",
  },
  {
    id: "2",
    Image: kamar,
    title: "Kamar Lavender Orichio",
    price: "Rp1.000.000 per malam",
    capacity: "2 Orang",
    type: "King Size",
  },
  {
    id: "3",
    Image: kamar,
    title: "Kamar Lavender Orichio",
    price: "Rp1.000.000 per malam",
    capacity: "2 Orang",
    type: "King Size",
  },
]

export const DummyListKamar = [
  {
    id: "1",
    Image: kamar,
    title: "Kamar Lavender Orichio",
    price: "Rp1.000.000 per malam",
    capacity: "2 Orang",
    type: "King Size",
  },
  {
    id: "2",
    Image: kamar,
    title: "Kamar Lavender Orichio",
    price: "Rp1.000.000 per malam",
    capacity: "2 Orang",
    type: "King Size",
  },
  {
    id: "3",
    Image: kamar,
    title: "Kamar Lavender Orichio",
    price: "Rp1.000.000 per malam",
    capacity: "2 Orang",
    type: "King Size",
  },
  {
    id: "4",
    Image: kamar,
    title: "Kamar Lavender Orichio",
    price: "Rp1.000.000 per malam",
    capacity: "2 Orang",
    type: "King Size",
  },
  {
    id: "5",
    Image: kamar,
    title: "Kamar Lavender Orichio",
    price: "Rp1.000.000 per malam",
    capacity: "2 Orang",
    type: "King Size",
  },
  {
    id: "6",
    Image: kamar,
    title: "Kamar Lavender Orichio",
    price: "Rp1.000.000 per malam",
    capacity: "2 Orang",
    type: "King Size",
  },
  {
    id: "7",
    Image: kamar,
    title: "Kamar Lavender Orichio",
    price: "Rp1.000.000 per malam",
    capacity: "2 Orang",
    type: "King Size",
  },
  {
    id: "8",
    Image: kamar,
    title: "Kamar Lavender Orichio",
    price: "Rp1.000.000 per malam",
    capacity: "2 Orang",
    type: "King Size",
  },
  {
    id: "9",
    Image: kamar,
    title: "Kamar Lavender Orichio",
    price: "Rp1.000.000 per malam",
    capacity: "2 Orang",
    type: "King Size",
  },
]

export const DummyRiwayat = [
  {
    id: "1",
    room: "Room Orchidio Lavandera Luxury",
    person: "Raymond Ananda",
    duration: "3 Malam",
    total: "2 Kamar",
    status: "Baru",
    date: "11 Januari 2023",
  },
  {
    id: "2",
    room: "Room Orchidio Lavandera Luxury",
    person: "Raymond Ananda",
    duration: "3 Malam",
    total: "2 Kamar",
    status: "Baru",
    date: "11 Januari 2023",
  },
  {
    id: "3",
    room: "Room Orchidio Lavandera Luxury",
    person: "Raymond Ananda",
    duration: "3 Malam",
    total: "2 Kamar",
    status: "Baru",
    date: "11 Januari 2023",
  },
  {
    id: "4",
    room: "Room Orchidio Lavandera Luxury",
    person: "Raymond Ananda",
    duration: "3 Malam",
    total: "2 Kamar",
    status: "Baru",
    date: "11 Januari 2023",
  },
  {
    id: "5",
    room: "Room Orchidio Lavandera Luxury",
    person: "Raymond Ananda",
    duration: "3 Malam",
    total: "2 Kamar",
    status: "Baru",
    date: "11 Januari 2023",
  },
];

export const DummyTable = [
  {
    no: "1",
    nomerKamar: "001",
    namaTipekamar: "Orchidia Lavander Premium",
    harga: "Rp1.000.000",
    foto: dummyFoto,
  },
  {
    no: "2",
    nomerKamar: "001",
    namaTipekamar: "Orchidia Lavander Premium",
    harga: "Rp1.000.000",
    foto: dummyFoto,
  },
  {
    no: "3",
    nomerKamar: "001",
    namaTipekamar: "Orchidia Lavander Premium",
    harga: "Rp1.000.000",
    foto: dummyFoto,
  },
  {
    no: "4",
    nomerKamar: "001",
    namaTipekamar: "Orchidia Lavander Premium",
    harga: "Rp1.000.000",
    foto: dummyFoto,
  },
  {
    no: "5",
    nomerKamar: "001",
    namaTipekamar: "Orchidia Lavander Premium",
    harga: "Rp1.000.000",
    foto: dummyFoto,
  },
  {
    no: "6",
    nomerKamar: "001",
    namaTipekamar: "Orchidia Lavander Premium",
    harga: "Rp1.000.000",
    foto: dummyFoto,
  },
  {
    no: "7",
    nomerKamar: "001",
    namaTipekamar: "Orchidia Lavander Premium",
    harga: "Rp1.000.000",
    foto: dummyFoto,
  },
  {
    no: "8",
    nomerKamar: "001",
    namaTipekamar: "Orchidia Lavander Premium",
    harga: "Rp1.000.000",
    foto: dummyFoto,
  },
  {
    no: "9",
    nomerKamar: "001",
    namaTipekamar: "Orchidia Lavander Premium",
    harga: "Rp1.000.000",
    foto: dummyFoto,
  },
  {
    no: "10",
    nomerKamar: "001",
    namaTipekamar: "Orchidia Lavander Premium",
    harga: "Rp1.000.000",
    foto: dummyFoto,
  },
]
